// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20220223101042_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Location");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("WarehouseId");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Cars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "West wing",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            Location = "East wing",
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 3,
                            Location = "Suid wing",
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 4,
                            Location = "Suid wing",
                            WarehouseId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Latitude");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Longitude");

                    b.HasKey("Id");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = "47.13111",
                            Longitude = "-61.54801"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = "15.95386",
                            Longitude = "7.06246"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = "39.12788",
                            Longitude = "-2.71398"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = "-70.84354",
                            Longitude = "132.22345"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CarId");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateAdded");

                    b.Property<bool>("Licensed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Licensed");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Model");

                    b.Property<double>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("Price");

                    b.Property<short>("YearModel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("YearModel");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Vehicles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Volkswagen",
                            Model = "Jetta III",
                            Price = 12947.52,
                            YearModel = (short)1995
                        },
                        new
                        {
                            Id = 2,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Chevrolet",
                            Model = "Corvette",
                            Price = 20019.639999999999,
                            YearModel = (short)2004
                        },
                        new
                        {
                            Id = 3,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Ford",
                            Model = "Expedition EL",
                            Price = 27323.419999999998,
                            YearModel = (short)2008
                        },
                        new
                        {
                            Id = 4,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Infiniti",
                            Model = "FX",
                            Price = 8541.6200000000008,
                            YearModel = (short)2010
                        },
                        new
                        {
                            Id = 5,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "GMC",
                            Model = "Safari",
                            Price = 14772.5,
                            YearModel = (short)1998
                        },
                        new
                        {
                            Id = 6,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Plymouth",
                            Model = "Colt Vista",
                            Price = 6642.4499999999998,
                            YearModel = (short)1994
                        },
                        new
                        {
                            Id = 7,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Cadillac",
                            Model = "Escalade ESV",
                            Price = 24925.75,
                            YearModel = (short)2008
                        },
                        new
                        {
                            Id = 8,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mitsubishi",
                            Model = "Pajero",
                            Price = 28619.450000000001,
                            YearModel = (short)2002
                        },
                        new
                        {
                            Id = 9,
                            CarId = 1,
                            DateAdded = new DateTime(2017, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Infiniti",
                            Model = "Q",
                            Price = 6103.3999999999996,
                            YearModel = (short)1995
                        },
                        new
                        {
                            Id = 10,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Ford",
                            Model = "Mustang",
                            Price = 18992.700000000001,
                            YearModel = (short)1993
                        },
                        new
                        {
                            Id = 11,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Chevrolet",
                            Model = "G-Series 1500",
                            Price = 23362.41,
                            YearModel = (short)1997
                        },
                        new
                        {
                            Id = 12,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Cadillac",
                            Model = "DeVille",
                            Price = 18371.529999999999,
                            YearModel = (short)1993
                        },
                        new
                        {
                            Id = 13,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Acura",
                            Model = "NSX",
                            Price = 23175.759999999998,
                            YearModel = (short)2001
                        },
                        new
                        {
                            Id = 14,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Ford",
                            Model = "Econoline E250",
                            Price = 26605.540000000001,
                            YearModel = (short)1994
                        },
                        new
                        {
                            Id = 15,
                            CarId = 1,
                            DateAdded = new DateTime(2017, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Lexus",
                            Model = "GX",
                            Price = 27395.259999999998,
                            YearModel = (short)2005
                        },
                        new
                        {
                            Id = 16,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Dodge",
                            Model = "Ram Van 3500",
                            Price = 6244.5100000000002,
                            YearModel = (short)1999
                        },
                        new
                        {
                            Id = 17,
                            CarId = 1,
                            DateAdded = new DateTime(2017, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Dodge",
                            Model = "Caravan",
                            Price = 16145.27,
                            YearModel = (short)1995
                        },
                        new
                        {
                            Id = 18,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Dodge",
                            Model = "Dynasty",
                            Price = 15103.84,
                            YearModel = (short)1992
                        },
                        new
                        {
                            Id = 19,
                            CarId = 1,
                            DateAdded = new DateTime(2018, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Dodge",
                            Model = "Ram 1500",
                            Price = 9977.6499999999996,
                            YearModel = (short)2004
                        },
                        new
                        {
                            Id = 20,
                            CarId = 2,
                            DateAdded = new DateTime(2017, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Maserati",
                            Model = "Coupe",
                            Price = 19957.709999999999,
                            YearModel = (short)2005
                        },
                        new
                        {
                            Id = 21,
                            CarId = 2,
                            DateAdded = new DateTime(2017, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Isuzu",
                            Model = "Rodeo",
                            Price = 6303.9899999999998,
                            YearModel = (short)1998
                        },
                        new
                        {
                            Id = 22,
                            CarId = 2,
                            DateAdded = new DateTime(2017, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Infiniti",
                            Model = "I",
                            Price = 6910.1599999999999,
                            YearModel = (short)2002
                        },
                        new
                        {
                            Id = 23,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Nissan",
                            Model = "Altima",
                            Price = 8252.6599999999999,
                            YearModel = (short)1994
                        },
                        new
                        {
                            Id = 24,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Toyota",
                            Model = "Corolla",
                            Price = 23732.110000000001,
                            YearModel = (short)2009
                        },
                        new
                        {
                            Id = 25,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Acura",
                            Model = "MDX",
                            Price = 8487.1900000000005,
                            YearModel = (short)2011
                        },
                        new
                        {
                            Id = 26,
                            CarId = 2,
                            DateAdded = new DateTime(2017, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "BMW",
                            Model = "7 Series",
                            Price = 29069.52,
                            YearModel = (short)1998
                        },
                        new
                        {
                            Id = 27,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Nissan",
                            Model = "Maxima",
                            Price = 11187.68,
                            YearModel = (short)2004
                        },
                        new
                        {
                            Id = 28,
                            CarId = 2,
                            DateAdded = new DateTime(2017, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Audi",
                            Model = "A8",
                            Price = 16047.9,
                            YearModel = (short)1999
                        },
                        new
                        {
                            Id = 29,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Nissan",
                            Model = "Murano",
                            Price = 25859.779999999999,
                            YearModel = (short)2005
                        },
                        new
                        {
                            Id = 30,
                            CarId = 2,
                            DateAdded = new DateTime(2017, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Acura",
                            Model = "RL",
                            Price = 13232.129999999999,
                            YearModel = (short)2010
                        },
                        new
                        {
                            Id = 31,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mitsubishi",
                            Model = "Chariot",
                            Price = 15665.23,
                            YearModel = (short)1987
                        },
                        new
                        {
                            Id = 32,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "GMC",
                            Model = "3500 Club Coupe",
                            Price = 18129.369999999999,
                            YearModel = (short)1992
                        },
                        new
                        {
                            Id = 33,
                            CarId = 2,
                            DateAdded = new DateTime(2017, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Dodge",
                            Model = "Dakota",
                            Price = 14479.370000000001,
                            YearModel = (short)2009
                        },
                        new
                        {
                            Id = 34,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mercury",
                            Model = "Grand Marquis",
                            Price = 20614.720000000001,
                            YearModel = (short)1996
                        },
                        new
                        {
                            Id = 35,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Kia",
                            Model = "Sportage",
                            Price = 27106.470000000001,
                            YearModel = (short)2001
                        },
                        new
                        {
                            Id = 36,
                            CarId = 2,
                            DateAdded = new DateTime(2017, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Chevrolet",
                            Model = "Blazer",
                            Price = 14835.48,
                            YearModel = (short)1994
                        },
                        new
                        {
                            Id = 37,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mercedes-Benz",
                            Model = "SL-Class",
                            Price = 27717.279999999999,
                            YearModel = (short)1994
                        },
                        new
                        {
                            Id = 38,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Honda",
                            Model = "Civic Si",
                            Price = 18569.860000000001,
                            YearModel = (short)2003
                        },
                        new
                        {
                            Id = 39,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Mercedes-Benz",
                            Model = "CL-Class",
                            Price = 23494.779999999999,
                            YearModel = (short)2002
                        },
                        new
                        {
                            Id = 40,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Volkswagen",
                            Model = "Jetta",
                            Price = 25469.490000000002,
                            YearModel = (short)2006
                        },
                        new
                        {
                            Id = 41,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Pontiac",
                            Model = "Grand Prix",
                            Price = 11600.74,
                            YearModel = (short)1975
                        },
                        new
                        {
                            Id = 42,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Infiniti",
                            Model = "FX",
                            Price = 22000.619999999999,
                            YearModel = (short)2012
                        },
                        new
                        {
                            Id = 43,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Jaguar",
                            Model = "XK",
                            Price = 10260.790000000001,
                            YearModel = (short)2006
                        },
                        new
                        {
                            Id = 44,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Cadillac",
                            Model = "STS",
                            Price = 13740.200000000001,
                            YearModel = (short)2007
                        },
                        new
                        {
                            Id = 45,
                            CarId = 2,
                            DateAdded = new DateTime(2017, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Pontiac",
                            Model = "Sunfire",
                            Price = 28489.099999999999,
                            YearModel = (short)1997
                        },
                        new
                        {
                            Id = 46,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Cadillac",
                            Model = "SRX",
                            Price = 26750.380000000001,
                            YearModel = (short)2004
                        },
                        new
                        {
                            Id = 47,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Land Rover",
                            Model = "Freelander",
                            Price = 21770.59,
                            YearModel = (short)2004
                        },
                        new
                        {
                            Id = 48,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Suzuki",
                            Model = "Forenza",
                            Price = 28834.259999999998,
                            YearModel = (short)2005
                        },
                        new
                        {
                            Id = 49,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Saab",
                            Model = "9-7X",
                            Price = 25975.68,
                            YearModel = (short)2005
                        },
                        new
                        {
                            Id = 50,
                            CarId = 2,
                            DateAdded = new DateTime(2018, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Ford",
                            Model = "Fusion",
                            Price = 28091.959999999999,
                            YearModel = (short)2012
                        },
                        new
                        {
                            Id = 51,
                            CarId = 3,
                            DateAdded = new DateTime(2018, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Cadillac",
                            Model = "Escalade",
                            Price = 7429.1800000000003,
                            YearModel = (short)2005
                        },
                        new
                        {
                            Id = 52,
                            CarId = 3,
                            DateAdded = new DateTime(2017, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Porsche",
                            Model = "Cayenne",
                            Price = 17066.310000000001,
                            YearModel = (short)2011
                        },
                        new
                        {
                            Id = 53,
                            CarId = 3,
                            DateAdded = new DateTime(2018, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mercedes-Benz",
                            Model = "SL-Class",
                            Price = 14066.059999999999,
                            YearModel = (short)2005
                        },
                        new
                        {
                            Id = 54,
                            CarId = 3,
                            DateAdded = new DateTime(2018, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mitsubishi",
                            Model = "RVR",
                            Price = 22560.18,
                            YearModel = (short)1995
                        },
                        new
                        {
                            Id = 55,
                            CarId = 3,
                            DateAdded = new DateTime(2017, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Volvo",
                            Model = "850",
                            Price = 25762.080000000002,
                            YearModel = (short)1995
                        },
                        new
                        {
                            Id = 56,
                            CarId = 3,
                            DateAdded = new DateTime(2017, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Honda",
                            Model = "del Sol",
                            Price = 18840.959999999999,
                            YearModel = (short)1994
                        },
                        new
                        {
                            Id = 57,
                            CarId = 3,
                            DateAdded = new DateTime(2018, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Infiniti",
                            Model = "Q",
                            Price = 28773.139999999999,
                            YearModel = (short)1996
                        },
                        new
                        {
                            Id = 58,
                            CarId = 3,
                            DateAdded = new DateTime(2018, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Mercedes-Benz",
                            Model = "500E",
                            Price = 17141.080000000002,
                            YearModel = (short)1992
                        },
                        new
                        {
                            Id = 59,
                            CarId = 3,
                            DateAdded = new DateTime(2018, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "GMC",
                            Model = "Envoy XL",
                            Price = 18983.52,
                            YearModel = (short)2002
                        },
                        new
                        {
                            Id = 60,
                            CarId = 3,
                            DateAdded = new DateTime(2018, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Volkswagen",
                            Model = "Touareg 2",
                            Price = 15611.219999999999,
                            YearModel = (short)2008
                        },
                        new
                        {
                            Id = 61,
                            CarId = 4,
                            DateAdded = new DateTime(2017, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Saab",
                            Model = "900",
                            Price = 8771.0,
                            YearModel = (short)1987
                        },
                        new
                        {
                            Id = 62,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mazda",
                            Model = "B-Series",
                            Price = 23407.59,
                            YearModel = (short)1998
                        },
                        new
                        {
                            Id = 63,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "GMC",
                            Model = "Sierra 3500",
                            Price = 5869.2299999999996,
                            YearModel = (short)2012
                        },
                        new
                        {
                            Id = 64,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Chevrolet",
                            Model = "Corvette",
                            Price = 16630.669999999998,
                            YearModel = (short)1964
                        },
                        new
                        {
                            Id = 65,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Toyota",
                            Model = "Tacoma",
                            Price = 11597.18,
                            YearModel = (short)1997
                        },
                        new
                        {
                            Id = 66,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "GMC",
                            Model = "Sonoma",
                            Price = 18248.209999999999,
                            YearModel = (short)2004
                        },
                        new
                        {
                            Id = 67,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Bugatti",
                            Model = "Veyron",
                            Price = 8051.6400000000003,
                            YearModel = (short)2009
                        },
                        new
                        {
                            Id = 68,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Dodge",
                            Model = "Ram 1500 Club",
                            Price = 14008.299999999999,
                            YearModel = (short)1996
                        },
                        new
                        {
                            Id = 69,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Land Rover",
                            Model = "Discovery Series II",
                            Price = 18620.189999999999,
                            YearModel = (short)2001
                        },
                        new
                        {
                            Id = 70,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Volvo",
                            Model = "960",
                            Price = 7316.9300000000003,
                            YearModel = (short)1993
                        },
                        new
                        {
                            Id = 71,
                            CarId = 4,
                            DateAdded = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Chrysler",
                            Model = "LHS",
                            Price = 29444.709999999999,
                            YearModel = (short)2001
                        },
                        new
                        {
                            Id = 72,
                            CarId = 4,
                            DateAdded = new DateTime(2017, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Porsche",
                            Model = "944",
                            Price = 7396.9499999999998,
                            YearModel = (short)1984
                        },
                        new
                        {
                            Id = 73,
                            CarId = 4,
                            DateAdded = new DateTime(2017, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Subaru",
                            Model = "Legacy",
                            Price = 24491.799999999999,
                            YearModel = (short)2010
                        },
                        new
                        {
                            Id = 74,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Volvo",
                            Model = "XC90",
                            Price = 29009.650000000001,
                            YearModel = (short)2003
                        },
                        new
                        {
                            Id = 75,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Buick",
                            Model = "Skyhawk",
                            Price = 10567.27,
                            YearModel = (short)1985
                        },
                        new
                        {
                            Id = 76,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "GMC",
                            Model = "Envoy XUV",
                            Price = 20997.709999999999,
                            YearModel = (short)2004
                        },
                        new
                        {
                            Id = 77,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Volvo",
                            Model = "S60",
                            Price = 28614.950000000001,
                            YearModel = (short)2009
                        },
                        new
                        {
                            Id = 78,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Pontiac",
                            Model = "Montana",
                            Price = 11221.139999999999,
                            YearModel = (short)2000
                        },
                        new
                        {
                            Id = 79,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Lexus",
                            Model = "RX",
                            Price = 23194.009999999998,
                            YearModel = (short)2002
                        },
                        new
                        {
                            Id = 80,
                            CarId = 4,
                            DateAdded = new DateTime(2018, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Lexus",
                            Model = "RX",
                            Price = 17805.450000000001,
                            YearModel = (short)2000
                        });
                });

            modelBuilder.Entity("Domain.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LocationId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Warehouses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationId = 1,
                            Name = "Warehouse A"
                        },
                        new
                        {
                            Id = 2,
                            LocationId = 2,
                            Name = "Warehouse B"
                        },
                        new
                        {
                            Id = 3,
                            LocationId = 3,
                            Name = "Warehouse C"
                        },
                        new
                        {
                            Id = 4,
                            LocationId = 4,
                            Name = "Warehouse D"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Car", b =>
                {
                    b.HasOne("Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("Domain.Entities.Car", "Car")
                        .WithMany("Vehicles")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Domain.Entities.Warehouse", b =>
                {
                    b.HasOne("Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Domain.Entities.Car", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
